"""
Use this file for all configurations
"""

ABUSEIPDB_API_KEY = "<ABUSEIPDB_API_KEY>"
VT_API_KEY = "<VT_API_KEY>"
MONGO_URI = "<MongoURI>"
EMAIL_SENDER = "<EMAIL_SENDER>"
EMAIL_PASSWORD = "<EMAIL_PASSWORD>"
EMAIL_RECEIVER = "<EMAIL_RECEIVER>"
